#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Fri Mar 20 01:10:18 +0530 2026
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab -wto a94173a97a804e29ad08aa9939c7282f --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot axis_cnn_mnist_1000_tb_behav xil_defaultlib.axis_cnn_mnist_1000_tb xil_defaultlib.glbl -log elaborate.log"
xelab -wto a94173a97a804e29ad08aa9939c7282f --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot axis_cnn_mnist_1000_tb_behav xil_defaultlib.axis_cnn_mnist_1000_tb xil_defaultlib.glbl -log elaborate.log

