#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Sat Mar 21 22:33:02 +0530 2026
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim tb_axis_cnn_mnist_full_behav -key {Behavioral:sim_1:Functional:tb_axis_cnn_mnist_full} -tclbatch tb_axis_cnn_mnist_full.tcl -view /media/nisitha/My_Passport/MOODLE/Vivado_projects/FPGA_based_CNN_Acclerator/fpga_based_cnn_v20/tb_top_behav.wcfg -log simulate.log"
xsim tb_axis_cnn_mnist_full_behav -key {Behavioral:sim_1:Functional:tb_axis_cnn_mnist_full} -tclbatch tb_axis_cnn_mnist_full.tcl -view /media/nisitha/My_Passport/MOODLE/Vivado_projects/FPGA_based_CNN_Acclerator/fpga_based_cnn_v20/tb_top_behav.wcfg -log simulate.log

