webtalk_init -webtalk_dir /media/nisitha/My_Passport/MOODLE/Vivado_projects/FPGA_based_CNN_Acclerator/fpga_based_cnn_v20/fpga_based_cnn_v20.sim/sim_1/behav/xsim/xsim.dir/tb_conv2_buf_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sat Mar 21 14:19:34 2026" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "5a07049d-ac6c-4375-a676-879ade10c9be" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "a94173a97a804e29ad08aa9939c7282f" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "12" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 22.04.5 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "13th Gen Intel(R) Core(TM) i5-13450HX" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "800.000 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "2495926550 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "76.54_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "115448_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3642563456 -regid "" -xml /media/nisitha/My_Passport/MOODLE/Vivado_projects/FPGA_based_CNN_Acclerator/fpga_based_cnn_v20/fpga_based_cnn_v20.sim/sim_1/behav/xsim/xsim.dir/tb_conv2_buf_behav/webtalk/usage_statistics_ext_xsim.xml -html /media/nisitha/My_Passport/MOODLE/Vivado_projects/FPGA_based_CNN_Acclerator/fpga_based_cnn_v20/fpga_based_cnn_v20.sim/sim_1/behav/xsim/xsim.dir/tb_conv2_buf_behav/webtalk/usage_statistics_ext_xsim.html -wdm /media/nisitha/My_Passport/MOODLE/Vivado_projects/FPGA_based_CNN_Acclerator/fpga_based_cnn_v20/fpga_based_cnn_v20.sim/sim_1/behav/xsim/xsim.dir/tb_conv2_buf_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
